[package]
name = "bevy_mod_raycast"
version = "0.5.1"
authors = ["Aevyrie <aevyrie@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Ray Casting for the Bevy Engine."
repository = "https://github.com/aevyrie/bevy_mod_raycast/"
keywords = ["gamedev", "graphics", "bevy", "3d", "raycast"]
categories = ["game-engines", "rendering"]
resolver = "2"

[dependencies]
bevy = {git = "https://github.com/paxsethorld/bevy-fork.git", branch = "local-0-8-release", default-features = false, features = [
    "render",
    "bevy_asset",
]}
# bevy = { version = "0.8", default-features = false, features = [
#     "render",
#     "bevy_asset",
# ] }

# [dev-dependencies]
# bevy = { version = "0.8", default-features = false, features = [
#     "bevy_scene",
#     "bevy_winit",
#     "x11",
# ] }
# criterion = "0.3"

[[bench]]
name = "ray_mesh_intersection"
harness = false
